version: '3'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./proxy/nginx.conf:/etc/nginx/nginx.conf
        depends_on: #db와 의존성 연결. (DB가 켜져있어야 실행댐.)
            - back
    back:
        build:
          context: .
        image: moazzi-back
        container_name: spring
        #environment:
          #- SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/fm #container 내부 포트 사용해야함.         
        expose:
            - "8080"
        restart: "unless-stopped"