spring:
  h2:
    console:
      enabled: true  # H2 콘솔 활성화
  datasource:
    url: ENC(xdBfa1rwrZ/LMvpSdHqKGv99u6o8raXkdnPw7Cej1Kw=) # H2 메모리 데이터베이스 URL
    driver-class-name: ENC(S2mR+IW0s5XhFHjY1FNnZnejn6N/0Nui) # H2 드라이버 클래스
    username: ENC(VB8JefN6TJVPd+AZ3Ke/OA==)  # 데이터베이스 사용자명
    password:   # 데이터베이스 암호


google:
