spring:
  datasource:
    driver-class-name: ENC(SojHfd7ZSvnUQCn1fMNHjv853XNoYAxYEuaibNt7HIU=)
    url: ENC(dUiPl2g8GblvMGvBox/I24yzLUkuOMBqbsDetxyRsNx7fLflF7YLnGJwuWa0etBzdsshIyq9ZbU2U1z7CLjy3ZJn3SWg2OI9dqvCKt1XFLidEr3U2RT/MiZd0XNHhGU3)
    username: ENC(No/sIV5zXfNA8r7ZLgQ9YQ==)
    password: ENC(39zNt69vfFEYVrTUPauqXK+YgSFqIuwv)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**

apikeys:
  festival: ENC(0YhxuUZupWN8ImReocB3uVKgHfjjSE7pKFUAubawybImQPKAKJ1fijcmgpZWPEyPzFxVyyJ7os8iOYplE6abw+BNpQejlmBHgJ/0s8C4Dq5x5/oTBpzjCeNMJu7G9fGvI3IhNIbRJw2kbqQmJ4zRGA==)
  permitArea: ENC(GMVikdnJhQKG3BXmRDxMo87JjsQU4a1JG6MhuLNCfVNoTmzEBdK2xkxlmsGUIm7Hz9LZX/7R9zXqSibK9PznWdVdveIkSuHN/pS/1D5aJJiOkrSOqksHuIhhlv7fg/8GeNIGtwrxYxF2E5TvgNuPdw==)

google:
