spring:
  h2:
    console:
      enabled: true  # H2 콘솔 활성화
  datasource:
    url: jdbc:h2:mem:testdb  # H2 메모리 데이터베이스 URL
    driver-class-name: org.h2.Driver  # H2 드라이버 클래스
    username: sa  # 데이터베이스 사용자명
    password:   # 데이터베이스 암호


google:
