spring:
  h2:
    console:
      enabled: true  # H2 콘솔 활성화
  datasource:
    url: ENC(xdBfa1rwrZ/LMvpSdHqKGv99u6o8raXkdnPw7Cej1Kw=) # H2 메모리 데이터베이스 URL
    driver-class-name: ENC(S2mR+IW0s5XhFHjY1FNnZnejn6N/0Nui) # H2 드라이버 클래스
    username: ENC(VB8JefN6TJVPd+AZ3Ke/OA==)  # 데이터베이스 사용자명
    password:   # 데이터베이스 암호

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
  paths-to-match:
    - /**

apikeys:
  festival: ENC(0YhxuUZupWN8ImReocB3uVKgHfjjSE7pKFUAubawybImQPKAKJ1fijcmgpZWPEyPzFxVyyJ7os8iOYplE6abw+BNpQejlmBHgJ/0s8C4Dq5x5/oTBpzjCeNMJu7G9fGvI3IhNIbRJw2kbqQmJ4zRGA==)

google:
