spring:
  datasource:
    driver-class-name: ENC(SojHfd7ZSvnUQCn1fMNHjv853XNoYAxYEuaibNt7HIU=)
    url: ENC(dUiPl2g8GblvMGvBox/I24yzLUkuOMBqbsDetxyRsNx7fLflF7YLnGJwuWa0etBzdsshIyq9ZbU2U1z7CLjy3ZJn3SWg2OI9dqvCKt1XFLidEr3U2RT/MiZd0XNHhGU3)
    username: ENC(No/sIV5zXfNA8r7ZLgQ9YQ==)
    password: ENC(39zNt69vfFEYVrTUPauqXK+YgSFqIuwv)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect

apikeys:
  festival: ENC(0YhxuUZupWN8ImReocB3uVKgHfjjSE7pKFUAubawybImQPKAKJ1fijcmgpZWPEyPzFxVyyJ7os8iOYplE6abw+BNpQejlmBHgJ/0s8C4Dq5x5/oTBpzjCeNMJu7G9fGvI3IhNIbRJw2kbqQmJ4zRGA==)

google:
